import type { TopicContent } from '../../types';

export const s3Content: TopicContent = {
  slug: 'aws/s3', title: 'AWS S3', category: 'aws',
  theory: `# AWS S3\n\nSimple Storage Service — scalable object storage. 11 nines of durability (99.999999999%).\n\n## Key Concepts\n\n- **Bucket** — container for objects (files). Globally unique name.\n- **Object** — file + metadata. Up to 5TB. Key = full path.\n- **Prefix** — simulated directory structure.\n\n## Storage Classes\n\n| Class | Access | Retrieval | Cost |\n|-------|--------|-----------|------|\n| Standard | Frequent | Instant | High |\n| Standard-IA | Infrequent | Instant | Medium |\n| One Zone-IA | Infrequent | Instant | Lower (1 AZ) |\n| Glacier Instant | Archive | Instant | Low |\n| Glacier Flexible | Archive | 1–12 hours | Very Low |\n| Glacier Deep Archive | Archive | Up to 12h | Lowest |\n| Intelligent Tiering | Unknown | Instant | Auto |\n\n## Versioning\n\nKeep multiple versions of objects. Protects against accidental deletion. Enables recovery.\n\n## Replication\n\n- **CRR (Cross-Region Replication)** — different region, compliance/DR\n- **SRR (Same-Region Replication)** — same region, different account\n\n## Security\n\n- Bucket Policy (resource-based) — allow public access or cross-account\n- ACL — legacy, prefer bucket policies\n- S3 Block Public Access — overrides any public permissions\n- SSE-S3, SSE-KMS, SSE-C — encryption at rest\n- TLS — encryption in transit\n\n## Pre-signed URLs\n\nTemporary URL to upload or download an object without AWS credentials.\n\`\`\`go\nclient.PresignGetObject(ctx, &s3.GetObjectInput{Bucket: &bucket, Key: &key}, func(o *s3.PresignOptions) { o.Expires = 15 * time.Minute })\n\`\`\`\n`,
  examples: `# S3 — Examples\n\n## Upload Object (Go SDK v2)\n\n\`\`\`go\ncfg, _ := config.LoadDefaultConfig(ctx)\nclient := s3.NewFromConfig(cfg)\n_, err := client.PutObject(ctx, &s3.PutObjectInput{\n    Bucket:      aws.String("my-bucket"),\n    Key:         aws.String("uploads/file.jpg"),\n    Body:        file,\n    ContentType: aws.String("image/jpeg"),\n})\n\`\`\`\n\n## Lifecycle Policy\n\nTransition objects to Glacier after 90 days, delete after 365 days.`,
  patterns: `# S3 Patterns\n\n## 1. Static website hosting — bucket + CloudFront CDN\n## 2. Pre-signed URL — temporary upload/download without exposing credentials\n## 3. Event notifications — S3 triggers Lambda on object upload\n## 4. Lifecycle policies — auto-transition to cheaper storage classes\n## 5. Multi-part upload — parallel upload of large objects (> 100MB)`,
  interviewTips: `# Interview Tips — S3\n\n1. S3 is eventually consistent for overwrites/deletes (now strongly consistent since Dec 2020).\n2. S3 can host static websites — combine with CloudFront for global CDN.\n3. Pre-signed URLs for temporary access without making bucket public.\n4. Lifecycle policies automate cost management.\n5. Cross-region replication for disaster recovery.`,
  commonMistakes: `# Common Mistakes — S3\n\n1. Making bucket public — exposes all objects.\n2. Not enabling versioning — can't recover deleted files.\n3. Not using lifecycle policies — paying for rarely accessed data.\n4. Forgetting S3 transfer costs — free to PUT, pay for GET and transfer out.`,
  revision: `# S3 — Quick Revision\n\n| Feature | Key |\n|---------|-----|\n| Durability | 99.999999999% (11 nines) |\n| Max object size | 5 TB |\n| Pre-signed URL | Temp access, configurable expiry |\n| Versioning | Multiple versions, deletion recovery |\n| CRR | Cross-region replication for DR |\n`,
  codeExamples: [],
  resources: [
    { title: 'AWS S3 Documentation', url: 'https://docs.aws.amazon.com/s3/index.html', type: 'docs', free: true },
    { title: 'S3 Storage Classes', url: 'https://aws.amazon.com/s3/storage-classes/', type: 'docs', free: true },
    { title: 'S3 Best Practices — GfG', url: 'https://www.geeksforgeeks.org/amazon-s3/', type: 'article', free: true },
  ],
  quiz: [
    { id: 's3-q1', question: 'What is the durability of S3 Standard?', options: ['99.9%', '99.99%', '99.9999999%', '99.999999999%'], correctIndex: 3, explanation: 'S3 Standard provides 11 nines of durability (99.999999999%) by redundantly storing data across multiple AZs and devices within an AZ.' },
    { id: 's3-q2', question: 'Pre-signed S3 URLs are used to:', options: ['Permanently grant public access', 'Grant temporary access to upload or download without credentials', 'Encrypt objects at rest', 'Enable versioning'], correctIndex: 1, explanation: 'Pre-signed URLs embed credentials and expiry time. Share with users for temporary file access without making the bucket public or sharing AWS credentials.' },
    { id: 's3-q3', question: 'S3 Intelligent-Tiering automatically:', options: ['Deletes old objects', 'Moves objects between storage tiers based on access patterns', 'Replicates to another region', 'Compresses objects'], correctIndex: 1, explanation: 'Intelligent-Tiering monitors access patterns and moves objects between Frequent and Infrequent tiers automatically — optimising cost without performance impact.' },
    { id: 's3-q4', question: 'For disaster recovery across AWS regions, use:', options: ['Same-Region Replication (SRR)', 'Cross-Region Replication (CRR)', 'Versioning only', 'Glacier'], correctIndex: 1, explanation: 'CRR asynchronously replicates objects to a bucket in a different AWS region. If the source region fails, you can failover to the replica.' },
  ],
  questions: [],
};
