import type { TopicContent } from '../../types';

export const rdsContent: TopicContent = {
  slug: 'aws/rds', title: 'AWS RDS', category: 'aws',
  theory: `# AWS RDS\n\nManaged relational database service. AWS handles backups, patching, failover.\n\n## Supported Engines\n\nMySQL, PostgreSQL, MariaDB, Oracle, SQL Server, **Aurora** (AWS-optimised)\n\n## Multi-AZ vs Read Replicas\n\n**Multi-AZ:**\n- Synchronous replication to standby in different AZ\n- Automatic failover ~1–2 minutes\n- For high availability, NOT performance\n\n**Read Replicas:**\n- Asynchronous replication\n- Up to 15 replicas\n- For read scaling and reporting queries\n- Can be in another region (cross-region RR)\n\n## Aurora\n\n- Up to 5x faster than MySQL, 3x faster than PostgreSQL\n- 6 copies of data across 3 AZs\n- Auto-scales storage 10 GB – 128 TB\n- Aurora Serverless: auto-scale compute\n- Global Database: <1s cross-region replication\n\n## RDS Proxy\n\nManaged connection pooler. Reduces connection overhead for Lambda/serverless workloads that open many short-lived connections.\n\n## Backups\n\n- Automated backups: 1–35 days retention, point-in-time recovery\n- Manual snapshots: kept indefinitely, survive instance deletion\n\n## Encryption\n\n- At rest: KMS encryption (must enable at creation)\n- In transit: SSL/TLS\n`,
  examples: `# RDS — Examples\n\n## Connection from Go (PostgreSQL)\n\n\`\`\`go\nimport (\n    "database/sql"\n    _ "github.com/lib/pq"\n)\ndsn := "host=db.example.us-east-1.rds.amazonaws.com port=5432 user=admin password=secret dbname=mydb sslmode=require"\ndb, err := sql.Open("postgres", dsn)\ndb.SetMaxOpenConns(25)\ndb.SetMaxIdleConns(25)\ndb.SetConnMaxLifetime(5 * time.Minute)\n\`\`\`\n\n## Use RDS Proxy for Lambda\n\nLambda creates new connections on each cold start. RDS Proxy pools them, preventing "too many connections" errors.`,
  patterns: `# RDS Patterns\n\n## 1. Multi-AZ for HA — automatic failover on primary failure\n## 2. Read Replicas for scale — offload read-heavy queries\n## 3. RDS Proxy — connection pooling for serverless/Lambda\n## 4. Aurora Global — multi-region with low-latency failover\n## 5. Parameter Groups — tune DB engine settings`,
  interviewTips: `# Interview Tips — RDS\n\n1. Multi-AZ = High Availability (failover). Read Replicas = Scale (performance).\n2. Use RDS Proxy when Lambda connects to RDS — prevents connection exhaustion.\n3. Aurora is 5x MySQL performance because of distributed storage.\n4. Encryption must be enabled at creation — can't enable on existing unencrypted DB.\n5. Use IAM authentication for RDS — no password, uses temporary tokens.`,
  commonMistakes: `# Common Mistakes — RDS\n\n1. Confusing Multi-AZ with Read Replicas — different purposes.\n2. Lambda directly to RDS — connection exhaustion. Use RDS Proxy.\n3. Not enabling encryption — can't enable after creation.\n4. No automated backups — can't do point-in-time recovery.\n5. Public RDS endpoint — should be in private subnet.`,
  revision: `# RDS — Quick Revision\n\n| Feature | Multi-AZ | Read Replica |\n|---------|----------|--------------|\n| Replication | Synchronous | Asynchronous |\n| Purpose | High Availability | Read Scaling |\n| Failover | Automatic | Manual promote |\n| Readable | No (standby) | Yes |\n`,
  codeExamples: [],
  resources: [
    { title: 'AWS RDS Documentation', url: 'https://docs.aws.amazon.com/rds/index.html', type: 'docs', free: true },
    { title: 'RDS Best Practices', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_BestPractices.html', type: 'docs', free: true },
    { title: 'Aurora Documentation', url: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/', type: 'docs', free: true },
  ],
  quiz: [
    { id: 'rds-q1', question: 'Multi-AZ RDS is primarily for:', options: ['Read performance scaling', 'High availability with automatic failover', 'Cross-region replication', 'Reducing storage costs'], correctIndex: 1, explanation: 'Multi-AZ creates a synchronous standby replica in a different AZ. If the primary fails, RDS automatically promotes the standby — typically in 1–2 minutes.' },
    { id: 'rds-q2', question: 'Read Replicas use which replication type?', options: ['Synchronous — writes confirmed on both primary and replica', 'Asynchronous — replica may lag', 'Streaming replication only', 'Block-level replication'], correctIndex: 1, explanation: 'Read Replicas use asynchronous replication — writes are acknowledged on the primary first, then propagated. Slight lag means replicas may serve slightly stale data.' },
    { id: 'rds-q3', question: 'Why use RDS Proxy with Lambda?', options: ['Faster queries', 'Prevents connection exhaustion by pooling DB connections', 'Enables IAM auth', 'Required by AWS'], correctIndex: 1, explanation: 'Lambda creates connections per invocation. At high concurrency, this exhausts RDS\'s connection limit. RDS Proxy pools and reuses connections across Lambda functions.' },
    { id: 'rds-q4', question: 'Aurora vs RDS MySQL: Aurora stores data:', options: ['Identically to MySQL', 'On a single EBS volume', 'Across 6 copies in 3 AZs on distributed storage', 'Only in memory'], correctIndex: 2, explanation: 'Aurora\'s distributed storage engine keeps 6 copies of data across 3 AZs. This provides higher durability and performance than standard RDS single-volume storage.' },
  ],
  questions: [],
};
