// Maps seed topic titles to content slugs
const MAP: Record<string, string> = {
  // DSA
  Arrays: 'dsa/arrays',
  Strings: 'dsa/strings',
  Hashing: 'dsa/hashing',
  'Binary Search': 'dsa/binary-search',
  'Linked List': 'dsa/linked-list',
  Stack: 'dsa/stack',
  Queue: 'dsa/queue',
  Heap: 'dsa/heap',
  Tree: 'dsa/tree',
  BST: 'dsa/bst',
  Trie: 'dsa/trie',
  Graph: 'dsa/graph',
  DFS: 'dsa/dfs',
  BFS: 'dsa/bfs',
  Backtracking: 'dsa/backtracking',
  Greedy: 'dsa/greedy',
  'Dynamic Programming': 'dsa/dynamic-programming',
  'Bit Manipulation': 'dsa/bit-manipulation',
  'Segment Tree': 'dsa/segment-tree',
  'Fenwick Tree': 'dsa/fenwick-tree',
  'Sliding Window': 'dsa/sliding-window',
  'Two Pointer': 'dsa/two-pointer',
  'Prefix Sum': 'dsa/prefix-sum',
  Math: 'dsa/math',
  Recursion: 'dsa/recursion',
  Sorting: 'dsa/sorting',
  Searching: 'dsa/searching',
  'Union Find': 'dsa/union-find',
  'Monotonic Stack': 'dsa/monotonic-stack',
  'Priority Queue': 'dsa/priority-queue',
  'Topological Sort': 'dsa/topological-sort',
  'Shortest Path': 'dsa/shortest-path',
  MST: 'dsa/graph',
  // System Design
  'CAP Theorem': 'system-design/cap-theorem',
  Scalability: 'system-design/scalability',
  'Load Balancer': 'system-design/load-balancer',
  Caching: 'system-design/caching',
  Redis: 'system-design/redis',
  NGINX: 'system-design/nginx',
  'API Gateway': 'system-design/api-gateway',
  'Reverse Proxy': 'system-design/load-balancer',
  'Database Replication': 'system-design/database-replication',
  Sharding: 'system-design/sharding',
  Partitioning: 'system-design/partitioning',
  Microservices: 'system-design/microservices',
  Monolith: 'system-design/microservices',
  'Event Driven Architecture': 'system-design/kafka',
  Kafka: 'system-design/kafka',
  RabbitMQ: 'system-design/kafka',
  SQS: 'system-design/kafka',
  CQRS: 'system-design/cqrs',
  'Rate Limiter': 'system-design/rate-limiter',
  'Circuit Breaker': 'system-design/microservices',
  'Distributed Lock': 'system-design/distributed-systems',
  ElasticSearch: 'system-design/distributed-systems',
  Logging: 'system-design/distributed-systems',
  Monitoring: 'system-design/distributed-systems',
  Prometheus: 'system-design/distributed-systems',
  Grafana: 'system-design/distributed-systems',
  OpenTelemetry: 'system-design/distributed-systems',
  Docker: 'system-design/microservices',
  Kubernetes: 'system-design/microservices',
  'CI/CD': 'system-design/microservices',
  // AWS
  IAM: 'aws/iam',
  EC2: 'aws/ec2',
  S3: 'aws/s3',
  VPC: 'aws/vpc',
  CloudFront: 'aws/cloudfront',
  Route53: 'aws/route53',
  RDS: 'aws/rds',
  'Auto Scaling': 'aws/ec2',
  Lambda: 'aws/lambda',
  DynamoDB: 'aws/dynamodb',
  CloudWatch: 'aws/cloudwatch',
  CloudFormation: 'aws/cloudformation',
  SNS: 'aws/sns-sqs',
  ECS: 'aws/ecs',
  EKS: 'aws/eks',
  'Elastic Beanstalk': 'aws/ec2',
  CodePipeline: 'aws/codepipeline',
  CodeDeploy: 'aws/codepipeline',
  // Golang
  'Go Basics': 'golang/goroutines',
  Pointers: 'golang/goroutines',
  Interfaces: 'golang/interfaces',
  Structs: 'golang/interfaces',
  Generics: 'golang/interfaces',
  Concurrency: 'golang/concurrency',
  Channels: 'golang/channels',
  Mutex: 'golang/concurrency',
  Context: 'golang/context',
  WaitGroup: 'golang/concurrency',
  'Worker Pool': 'golang/concurrency',
  'REST API': 'golang/rest-api',
  gRPC: 'golang/grpc',
  JWT: 'golang/rest-api',
  OAuth: 'golang/rest-api',
  'Redis (Go)': 'golang/concurrency',
  'Kafka (Go)': 'golang/concurrency',
  'RabbitMQ (Go)': 'golang/concurrency',
  'MongoDB (Go)': 'golang/rest-api',
  'PostgreSQL (Go)': 'golang/rest-api',
  'Docker (Go)': 'golang/concurrency',
  'Kubernetes (Go)': 'golang/concurrency',
  'Microservices (Go)': 'golang/clean-architecture',
  'Hexagonal Architecture': 'golang/clean-architecture',
  'Clean Architecture': 'golang/clean-architecture',
  Testing: 'golang/testing',
  Benchmarking: 'golang/testing',
  Profiling: 'golang/testing',
  Security: 'golang/rest-api',
  'Rate Limiting': 'golang/rest-api',
  // Interview
  'Behavioral Questions': 'interview/behavioral',
  'STAR Method': 'interview/behavioral',
  'Mock Interviews': 'interview/coding-interviews',
  'Resume Tips': 'interview/behavioral',
  'Salary Negotiation': 'interview/salary-negotiation',
  'Company Research': 'interview/behavioral',
  Whiteboarding: 'interview/coding-interviews',
  'System Design Interviews': 'interview/system-design-interview',
  'Coding Interview Tips': 'interview/coding-interviews',
  'Final Checklist': 'interview/coding-interviews',
};

export function getContentSlug(topicTitle: string): string {
  return MAP[topicTitle] ?? '';
}
