import type { TopicContent } from '../../types';

export const lambdaContent: TopicContent = {
  slug: 'aws/lambda', title: 'AWS Lambda', category: 'aws',
  theory: `# AWS Lambda\n\nServerless, event-driven function execution. Run code without managing servers.\n\n## Key Properties\n\n- Max execution time: 15 minutes\n- Memory: 128 MB – 10 GB (CPU scales with memory)\n- Ephemeral storage: /tmp up to 10 GB\n- Concurrency: 1000 default (can increase)\n- Package: zip or container image (up to 10 GB)\n\n## Execution Model\n\n**Cold start** — first invocation: download code, init runtime, run init code.\n**Warm execution** — subsequent invocations reuse the container.\n\nMinimise cold starts:\n- Provisioned Concurrency\n- Smaller deployment packages\n- Avoid heavy init code\n\n## Triggers\n\n| Trigger | Use Case |\n|---------|----------|\n| API Gateway | HTTP endpoints |\n| S3 | Process uploads |\n| SQS | Message processing |\n| SNS | Event notifications |\n| EventBridge | Scheduled jobs, events |\n| DynamoDB Streams | React to DB changes |\n| Kinesis | Stream processing |\n\n## Concurrency\n\n**Reserved concurrency** — cap function's max concurrent executions.\n**Provisioned concurrency** — pre-warmed instances, eliminates cold starts.\n\n## Layers\n\nShared code/dependencies packaged separately, reusable across Lambda functions.\n`,
  examples: `# Lambda — Examples\n\n## Go Lambda Handler\n\n\`\`\`go\npackage main\nimport (\n    "github.com/aws/aws-lambda-go/lambda"\n    "github.com/aws/aws-lambda-go/events"\n)\nfunc handler(req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {\n    return events.APIGatewayProxyResponse{\n        StatusCode: 200,\n        Body:       \`{"message": "hello"}\`,\n        Headers:    map[string]string{"Content-Type": "application/json"},\n    }, nil\n}\nfunc main() { lambda.Start(handler) }\n\`\`\`\n\n## SQS Batch Processing\n\n\`\`\`go\nfunc handler(ctx context.Context, event events.SQSEvent) error {\n    for _, record := range event.Records {\n        if err := processMessage(record.Body); err != nil {\n            return err // Lambda retries the batch\n        }\n    }\n    return nil\n}\n\`\`\``,
  patterns: `# Lambda Patterns\n\n## 1. API Gateway + Lambda — serverless REST API\n## 2. S3 Trigger — process uploads asynchronously\n## 3. SQS + Lambda — serverless message consumer\n## 4. EventBridge — cron jobs, cross-service events\n## 5. DynamoDB Streams — react to data changes\n## 6. Lambda@Edge — run at CloudFront edge locations`,
  interviewTips: `# Interview Tips — Lambda\n\n1. Cold start mitigations: Provisioned Concurrency, keep function warm with pings.\n2. Lambda is stateless — use S3/DynamoDB/ElasticCache for persistence.\n3. Always set function timeout and memory appropriately — CPU scales with memory.\n4. Use Dead Letter Queue (DLQ) for failed async invocations.\n5. Lambda concurrency = max simultaneous executions, not throughput.`,
  commonMistakes: `# Common Mistakes — Lambda\n\n1. No DLQ for async invocations — failures disappear silently.\n2. Large deployment packages — slow cold starts.\n3. Storing state in Lambda — stateless by design.\n4. Not handling partial batch failures in SQS processing.\n5. Default timeout too short or too long.`,
  revision: `# Lambda — Quick Revision\n\n| Limit | Value |\n|-------|-------|\n| Max timeout | 15 minutes |\n| Memory range | 128 MB – 10 GB |\n| Default concurrency | 1,000 |\n| Package size (zip) | 50 MB compressed |\n| Container image | Up to 10 GB |\n| /tmp storage | Up to 10 GB |\n`,
  codeExamples: [],
  resources: [
    { title: 'AWS Lambda Documentation', url: 'https://docs.aws.amazon.com/lambda/index.html', type: 'docs', free: true },
    { title: 'Lambda Go SDK', url: 'https://github.com/aws/aws-lambda-go', type: 'github', free: true },
    { title: 'Lambda Best Practices', url: 'https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html', type: 'docs', free: true },
  ],
  quiz: [
    { id: 'lmb-q1', question: 'What is a Lambda cold start?', options: ['Function timeout', 'First invocation overhead: download code, init runtime, run init', 'Memory limit exceeded', 'Concurrency limit hit'], correctIndex: 1, explanation: 'Cold start = no warm container available. AWS must: download code, initialise the runtime, and run your init() code. Can add 100ms–1s of latency.' },
    { id: 'lmb-q2', question: 'Provisioned Concurrency does what?', options: ['Increases concurrency limit', 'Pre-warms a set number of instances to eliminate cold starts', 'Reduces memory usage', 'Enables VPC access'], correctIndex: 1, explanation: 'Provisioned Concurrency keeps a specified number of execution environments initialised and ready, eliminating cold start latency for that capacity.' },
    { id: 'lmb-q3', question: 'Lambda functions scale by:', options: ['Thread pool per instance', 'Vertical scaling (more CPU per request)', 'Horizontal scaling (one new instance per concurrent request)', 'Fixed pool of 10 instances'], correctIndex: 2, explanation: 'Each concurrent invocation gets its own execution environment. 1000 concurrent requests = 1000 Lambda instances running in parallel (up to concurrency limit).' },
    { id: 'lmb-q4', question: 'For failed async Lambda invocations, best practice is:', options: ['Ignore failures', 'Add a Dead Letter Queue (SQS or SNS)', 'Set memory to maximum', 'Use synchronous invocation instead'], correctIndex: 1, explanation: 'Async failures are silent by default. Configure a DLQ to receive failed events so you can investigate, replay, or alert on them.' },
  ],
  questions: [],
};
