import type { TopicContent } from '../../types';

export const iamContent: TopicContent = {
  slug: 'aws/iam', title: 'AWS IAM', category: 'aws',
  theory: `# AWS IAM\n\nIdentity and Access Management — controls who can do what in AWS.\n\n## Core Concepts\n\n**Users** — long-term credentials, login to console or API.\n**Groups** — collection of users. Permissions applied at group level.\n**Roles** — temporary credentials. Assumed by services, users, or external identities.\n**Policies** — JSON documents defining permissions.\n\n## Policy Types\n\n**Identity policies** — attached to users/groups/roles.\n**Resource policies** — attached to resources (S3 bucket policy, KMS key policy).\n**Permission boundaries** — max permissions a role/user can have.\n\n## Policy Structure\n\n\`\`\`json\n{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Action": ["s3:GetObject", "s3:PutObject"],\n    "Resource": "arn:aws:s3:::my-bucket/*",\n    "Condition": { "StringEquals": { "aws:RequestedRegion": "us-east-1" } }\n  }]\n}\n\`\`\`\n\n## Least Privilege\n\nGrant only the permissions required. Start with deny-all, add specific allows.\n\n## Roles for Services\n\nEC2, Lambda, ECS tasks assume roles. Never embed credentials in code — use IAM roles.\n\n## STS (Security Token Service)\n\nAssume-role returns temporary credentials (access key, secret, session token, expiry).\n`,
  examples: `# IAM — Examples\n\n## EC2 Instance Role (No Hardcoded Keys)\n\n\`\`\`go\n// Use AWS SDK — automatically picks up role credentials\ncfg, _ := config.LoadDefaultConfig(context.Background())\ns3Client := s3.NewFromConfig(cfg)\n\`\`\`\n\n## Cross-Account Role\n\nAccount A has S3 bucket. Account B Lambda needs access.\n1. Account A: create role with trust policy allowing Account B to assume it.\n2. Account B Lambda: assumes the role via STS, gets temp credentials.`,
  patterns: `# IAM Patterns\n\n## 1. Least Privilege — deny all, add specific allows\n## 2. Role per service — each Lambda/ECS task has its own role\n## 3. Cross-account access — role + trust policy\n## 4. Break-glass account — emergency high-privilege role, rarely used\n## 5. Permission boundary — limit max permissions for dev-created roles`,
  interviewTips: `# Interview Tips — IAM\n\n1. Never use root account for daily operations — create IAM users/roles.\n2. Use roles for AWS services — never access keys hardcoded.\n3. Enable MFA for all users, especially admins.\n4. Use service control policies (SCPs) at org level to enforce guardrails.`,
  commonMistakes: `# Common Mistakes — IAM\n\n1. Hardcoding credentials in code — huge security risk.\n2. Using root account for automation.\n3. Wildcard (*) Actions and Resources — too permissive.\n4. Not rotating access keys regularly.`,
  revision: `# IAM — Quick Revision\n\n| Concept | One-liner |\n|---------|----------|\n| User | Long-term identity, login credentials |\n| Group | Collection of users, inherit policies |\n| Role | Temporary credentials for services/users |\n| Policy | JSON permission document |\n| STS | Issues temporary credentials for assume-role |\n`,
  codeExamples: [],
  resources: [
    { title: 'AWS IAM Documentation', url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/', type: 'docs', free: true },
    { title: 'IAM Best Practices', url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html', type: 'docs', free: true },
    { title: 'AWS IAM — FreeCodeCamp', url: 'https://www.freecodecamp.org/news/aws-iam-explained/', type: 'article', free: true },
  ],
  quiz: [
    { id: 'iam-q1', question: 'For an EC2 instance to access S3, the best practice is:', options: ['Embed access keys in user data', 'Hardcode credentials in the application', 'Attach an IAM role to the EC2 instance', 'Use the root account credentials'], correctIndex: 2, explanation: 'IAM roles for EC2 provide temporary credentials rotated automatically. No credentials are stored on the instance. Applications use the SDK to retrieve them automatically.' },
    { id: 'iam-q2', question: 'What does STS AssumeRole return?', options: ['Permanent IAM credentials', 'A new IAM user', 'Temporary access key, secret key, and session token with expiry', 'An IAM policy'], correctIndex: 2, explanation: 'AssumeRole returns temporary security credentials (access key ID, secret access key, session token) valid for up to 12 hours by default.' },
    { id: 'iam-q3', question: 'Least privilege principle means:', options: ['Users have no permissions', 'Grant only the minimum permissions required for the task', 'All services share one role', 'Policies are applied at account level only'], correctIndex: 1, explanation: 'Grant users, roles, and services only the permissions they need to perform their specific tasks. Start with deny-all and explicitly allow what\'s needed.' },
    { id: 'iam-q4', question: 'Permission Boundaries define:', options: ['The maximum permissions an IAM entity can ever have', 'The minimum required permissions', 'Cross-account trust relationships', 'Resource-level policies'], correctIndex: 0, explanation: 'A permission boundary sets the maximum permissions that an identity-based policy can grant. Even if a user has admin rights, they can\'t exceed the boundary.' },
  ],
  questions: [],
};
